/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterInfoSpecApplyConfiguration represents a declarative configuration of the ClusterInfoSpec type for use
// with apply.
type ClusterInfoSpecApplyConfiguration struct {
	ClusterID   *string                         `json:"clusterID,omitempty"`
	ServiceCIDR []string                        `json:"serviceCIDR,omitempty"`
	ClusterCIDR []string                        `json:"clusterCIDR,omitempty"`
	GlobalCIDR  []string                        `json:"globalCIDR,omitempty"`
	Networks    []NetworkInfoApplyConfiguration `json:"networks,omitempty"`
}

// ClusterInfoSpecApplyConfiguration constructs a declarative configuration of the ClusterInfoSpec type for use with
// apply.
func ClusterInfoSpec() *ClusterInfoSpecApplyConfiguration {
	return &ClusterInfoSpecApplyConfiguration{}
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ClusterInfoSpecApplyConfiguration) WithClusterID(value string) *ClusterInfoSpecApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithServiceCIDR adds the given value to the ServiceCIDR field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServiceCIDR field.
func (b *ClusterInfoSpecApplyConfiguration) WithServiceCIDR(values ...string) *ClusterInfoSpecApplyConfiguration {
	for i := range values {
		b.ServiceCIDR = append(b.ServiceCIDR, values[i])
	}
	return b
}

// WithClusterCIDR adds the given value to the ClusterCIDR field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterCIDR field.
func (b *ClusterInfoSpecApplyConfiguration) WithClusterCIDR(values ...string) *ClusterInfoSpecApplyConfiguration {
	for i := range values {
		b.ClusterCIDR = append(b.ClusterCIDR, values[i])
	}
	return b
}

// WithGlobalCIDR adds the given value to the GlobalCIDR field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GlobalCIDR field.
func (b *ClusterInfoSpecApplyConfiguration) WithGlobalCIDR(values ...string) *ClusterInfoSpecApplyConfiguration {
	for i := range values {
		b.GlobalCIDR = append(b.GlobalCIDR, values[i])
	}
	return b
}

// WithNetworks adds the given value to the Networks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Networks field.
func (b *ClusterInfoSpecApplyConfiguration) WithNetworks(values ...*NetworkInfoApplyConfiguration) *ClusterInfoSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNetworks")
		}
		b.Networks = append(b.Networks, *values[i])
	}
	return b
}
