/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndpointInfoApplyConfiguration represents a declarative configuration of the EndpointInfo type for use
// with apply.
type EndpointInfoApplyConfiguration struct {
	Address  *string `json:"address,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	NodeName *string `json:"nodeName,omitempty"`
	Zone     *string `json:"zone,omitempty"`
	Ready    *bool   `json:"ready,omitempty"`
}

// EndpointInfoApplyConfiguration constructs a declarative configuration of the EndpointInfo type for use with
// apply.
func EndpointInfo() *EndpointInfoApplyConfiguration {
	return &EndpointInfoApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *EndpointInfoApplyConfiguration) WithAddress(value string) *EndpointInfoApplyConfiguration {
	b.Address = &value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *EndpointInfoApplyConfiguration) WithHostname(value string) *EndpointInfoApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *EndpointInfoApplyConfiguration) WithNodeName(value string) *EndpointInfoApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithZone sets the Zone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zone field is set to the value of the last call.
func (b *EndpointInfoApplyConfiguration) WithZone(value string) *EndpointInfoApplyConfiguration {
	b.Zone = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *EndpointInfoApplyConfiguration) WithReady(value bool) *EndpointInfoApplyConfiguration {
	b.Ready = &value
	return b
}
