/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EVPNInfoApplyConfiguration represents a declarative configuration of the EVPNInfo type for use
// with apply.
type EVPNInfoApplyConfiguration struct {
	IPVRFVNI          *int32  `json:"ipvrfVNI,omitempty"`
	IPVRFRouteTarget  *string `json:"ipvrfRouteTarget,omitempty"`
	MACVRFVNI         *int32  `json:"macvrfVNI,omitempty"`
	MACVRFRouteTarget *string `json:"macvrfRouteTarget,omitempty"`
	ASN               *int32  `json:"asn,omitempty"`
}

// EVPNInfoApplyConfiguration constructs a declarative configuration of the EVPNInfo type for use with
// apply.
func EVPNInfo() *EVPNInfoApplyConfiguration {
	return &EVPNInfoApplyConfiguration{}
}

// WithIPVRFVNI sets the IPVRFVNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPVRFVNI field is set to the value of the last call.
func (b *EVPNInfoApplyConfiguration) WithIPVRFVNI(value int32) *EVPNInfoApplyConfiguration {
	b.IPVRFVNI = &value
	return b
}

// WithIPVRFRouteTarget sets the IPVRFRouteTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPVRFRouteTarget field is set to the value of the last call.
func (b *EVPNInfoApplyConfiguration) WithIPVRFRouteTarget(value string) *EVPNInfoApplyConfiguration {
	b.IPVRFRouteTarget = &value
	return b
}

// WithMACVRFVNI sets the MACVRFVNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACVRFVNI field is set to the value of the last call.
func (b *EVPNInfoApplyConfiguration) WithMACVRFVNI(value int32) *EVPNInfoApplyConfiguration {
	b.MACVRFVNI = &value
	return b
}

// WithMACVRFRouteTarget sets the MACVRFRouteTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACVRFRouteTarget field is set to the value of the last call.
func (b *EVPNInfoApplyConfiguration) WithMACVRFRouteTarget(value string) *EVPNInfoApplyConfiguration {
	b.MACVRFRouteTarget = &value
	return b
}

// WithASN sets the ASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ASN field is set to the value of the last call.
func (b *EVPNInfoApplyConfiguration) WithASN(value int32) *EVPNInfoApplyConfiguration {
	b.ASN = &value
	return b
}
