/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/discovery/v1"
)

// ServiceExportSpecApplyConfiguration represents a declarative configuration of the ServiceExportSpec type for use
// with apply.
type ServiceExportSpecApplyConfiguration struct {
	ServiceName      *string           `json:"serviceName,omitempty"`
	ServiceNamespace *string           `json:"serviceNamespace,omitempty"`
	Ports            []v1.EndpointPort `json:"ports,omitempty"`
}

// ServiceExportSpecApplyConfiguration constructs a declarative configuration of the ServiceExportSpec type for use with
// apply.
func ServiceExportSpec() *ServiceExportSpecApplyConfiguration {
	return &ServiceExportSpecApplyConfiguration{}
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *ServiceExportSpecApplyConfiguration) WithServiceName(value string) *ServiceExportSpecApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithServiceNamespace sets the ServiceNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceNamespace field is set to the value of the last call.
func (b *ServiceExportSpecApplyConfiguration) WithServiceNamespace(value string) *ServiceExportSpecApplyConfiguration {
	b.ServiceNamespace = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *ServiceExportSpecApplyConfiguration) WithPorts(values ...v1.EndpointPort) *ServiceExportSpecApplyConfiguration {
	for i := range values {
		b.Ports = append(b.Ports, values[i])
	}
	return b
}
