/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ServiceExportStatusApplyConfiguration represents a declarative configuration of the ServiceExportStatus type for use
// with apply.
type ServiceExportStatusApplyConfiguration struct {
	ClusterID    *string                          `json:"clusterID,omitempty"`
	NetworkName  *string                          `json:"networkName,omitempty"`
	ClusterSetIP *string                          `json:"clusterSetIP,omitempty"`
	Endpoints    []EndpointInfoApplyConfiguration `json:"endpoints,omitempty"`
	Conditions   []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ServiceExportStatusApplyConfiguration constructs a declarative configuration of the ServiceExportStatus type for use with
// apply.
func ServiceExportStatus() *ServiceExportStatusApplyConfiguration {
	return &ServiceExportStatusApplyConfiguration{}
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ServiceExportStatusApplyConfiguration) WithClusterID(value string) *ServiceExportStatusApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithNetworkName sets the NetworkName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkName field is set to the value of the last call.
func (b *ServiceExportStatusApplyConfiguration) WithNetworkName(value string) *ServiceExportStatusApplyConfiguration {
	b.NetworkName = &value
	return b
}

// WithClusterSetIP sets the ClusterSetIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterSetIP field is set to the value of the last call.
func (b *ServiceExportStatusApplyConfiguration) WithClusterSetIP(value string) *ServiceExportStatusApplyConfiguration {
	b.ClusterSetIP = &value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *ServiceExportStatusApplyConfiguration) WithEndpoints(values ...*EndpointInfoApplyConfiguration) *ServiceExportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ServiceExportStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ServiceExportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
