/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ovnbrokerv1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ovnbroker/v1alpha1"
	applyconfigurationovnbrokerv1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ovnbroker/v1alpha1/apis/applyconfiguration/ovnbroker/v1alpha1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ovnbroker/v1alpha1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterInfosGetter has a method to return a ClusterInfoInterface.
// A group's client should implement this interface.
type ClusterInfosGetter interface {
	ClusterInfos() ClusterInfoInterface
}

// ClusterInfoInterface has methods to work with ClusterInfo resources.
type ClusterInfoInterface interface {
	Create(ctx context.Context, clusterInfo *ovnbrokerv1alpha1.ClusterInfo, opts v1.CreateOptions) (*ovnbrokerv1alpha1.ClusterInfo, error)
	Update(ctx context.Context, clusterInfo *ovnbrokerv1alpha1.ClusterInfo, opts v1.UpdateOptions) (*ovnbrokerv1alpha1.ClusterInfo, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterInfo *ovnbrokerv1alpha1.ClusterInfo, opts v1.UpdateOptions) (*ovnbrokerv1alpha1.ClusterInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ovnbrokerv1alpha1.ClusterInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*ovnbrokerv1alpha1.ClusterInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ovnbrokerv1alpha1.ClusterInfo, err error)
	Apply(ctx context.Context, clusterInfo *applyconfigurationovnbrokerv1alpha1.ClusterInfoApplyConfiguration, opts v1.ApplyOptions) (result *ovnbrokerv1alpha1.ClusterInfo, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterInfo *applyconfigurationovnbrokerv1alpha1.ClusterInfoApplyConfiguration, opts v1.ApplyOptions) (result *ovnbrokerv1alpha1.ClusterInfo, err error)
	ClusterInfoExpansion
}

// clusterInfos implements ClusterInfoInterface
type clusterInfos struct {
	*gentype.ClientWithListAndApply[*ovnbrokerv1alpha1.ClusterInfo, *ovnbrokerv1alpha1.ClusterInfoList, *applyconfigurationovnbrokerv1alpha1.ClusterInfoApplyConfiguration]
}

// newClusterInfos returns a ClusterInfos
func newClusterInfos(c *BrokerV1alpha1Client) *clusterInfos {
	return &clusterInfos{
		gentype.NewClientWithListAndApply[*ovnbrokerv1alpha1.ClusterInfo, *ovnbrokerv1alpha1.ClusterInfoList, *applyconfigurationovnbrokerv1alpha1.ClusterInfoApplyConfiguration](
			"clusterinfos",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ovnbrokerv1alpha1.ClusterInfo { return &ovnbrokerv1alpha1.ClusterInfo{} },
			func() *ovnbrokerv1alpha1.ClusterInfoList { return &ovnbrokerv1alpha1.ClusterInfoList{} },
		),
	}
}
