/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ovnbrokerv1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ovnbroker/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterInfoLister helps list ClusterInfos.
// All objects returned here must be treated as read-only.
type ClusterInfoLister interface {
	// List lists all ClusterInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ovnbrokerv1alpha1.ClusterInfo, err error)
	// Get retrieves the ClusterInfo from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ovnbrokerv1alpha1.ClusterInfo, error)
	ClusterInfoListerExpansion
}

// clusterInfoLister implements the ClusterInfoLister interface.
type clusterInfoLister struct {
	listers.ResourceIndexer[*ovnbrokerv1alpha1.ClusterInfo]
}

// NewClusterInfoLister returns a new ClusterInfoLister.
func NewClusterInfoLister(indexer cache.Indexer) ClusterInfoLister {
	return &clusterInfoLister{listers.New[*ovnbrokerv1alpha1.ClusterInfo](indexer, ovnbrokerv1alpha1.Resource("clusterinfo"))}
}
